config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :search_queries

  get "trending" => "search_queries#trending", as: :trending_search_queries
  get "analytics" => "search_queries#analytics", as: :analytics_search_queries
  get "top_searches" => "search_queries#top_searches", as: :top_search_queries

  # Defines the root path route ("/")
  root "search_queries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/search_query.rb
class SearchQuery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/search_queries_controller.rb
class SearchQueriesController < ApplicationController
  def index; end

  def create
    @query = SearchQuery.new(search_query_params)
    @query.ip_address = request.remote_ip
    article = Article.find_by(title: @query.term)

    respond_to do |format|
      if article && @query.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("last_queries", partial: "search_queries/partials/query_results", locals: { articles: show_articles }),
            turbo_stream.replace("sub_menu", partial: "search_queries/partials/trending", locals: { trending: SearchQuery.group(:term).order('count_id DESC').limit(5).count(:id) })
          ]
        end
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("last_queries", partial: "search_queries/partials/query_results", locals: { articles: show_articles }),
            turbo_stream.replace("sub_menu", partial: "search_queries/partials/trending", locals: { trending: SearchQuery.group(:term).order('count_id DESC').limit(5).count(:id) })
          ]
        end
      end
    end
  end

  def trending
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("sub_menu", partial: "search_queries/partials/trending", locals: { trending: SearchQuery.group(:term).order('count_id DESC').limit(5).count(:id) })
        ]
      end
    end
  end

  def analytics
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("sub_menu", partial: "search_queries/partials/analytics", locals: { analytics: SearchQuery.where(ip_address: request.remote_ip) })
        ]
      end
    end
  end

  def top_searches
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("analytics", partial: "search_queries/partials/top_ten_queries_analytics", locals: { analytics: SearchQuery.where(ip_address: request.remote_ip).group(:term).order('count_id DESC').limit(10).count(:id) })
        ]
      end
    end
  end

  private

  def search_query_params
    params.require(:search_query).permit(:term, :ip_address)
  end

  def show_articles
    if params[:search_query][:term].blank?
      return Article.none
    else
      return Article.where("title LIKE ?", "%#{@query.term}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_queries_helper.rb
module SearchQueriesHelper
  def all_trending_queries
    SearchQuery.group(:term).order('count_id DESC').limit(5).count(:id)
  end

  def format_trend_information(trend)
    return if trend.blank?

    "#{trend.first} (#{trend.last} hits)"
  end
  
  def format_analytics_information(analytic)
    return if analytic.blank?

    "Term: #{analytic.term} | (From #{analytic.ip_address})"
  end
  
  def format_top_ten_information(analytic)
    return if analytic.blank?

    "Term: #{analytic.first} (#{analytic.last} hits)"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Search Box Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <% if notice || alert%>
      <div class="fixed top-0 left-0 right-0 z-50 bg-white shadow-md p-2">
        <%= notice ? notice : alert %>
      </div>
    <% end %>

    <main class="container w-3/4 mx-auto mt-28 px-5">
      <div class="flex justify-end mb-2">
        <div class="mx-2 bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition ease-in-out">
          <%= link_to "Trending Searches", trending_search_queries_path, data: { turbo_stream: true } %>
        </div>
        <div class="mx-2 bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition ease-in-out">
          <%= link_to "Analytics", analytics_search_queries_path, data: { turbo_stream: true } %>
        </div>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/search_queries/index.html.erb
<div class="w-full flex flex-col items-center bg-gray-200 p-8 rounded-lg shadow-lg">
  <div class="container w-3/4 p-4">
    <h1 class="text-3xl font-bold mb-4">Search Page</h1>
    <%= form_with model: SearchQuery, data: { turbo: true, controller: 'auto-submit' } do |form| %>
      <%= form.label 'Article', class: 'font-bold' %>
      <div class="flex flex-row h-8 justify-between items-center mt-2">
        <%= form.text_field :term, class: 'border rounded w-full mr-2 p-1 bg-white', data: { action: 'keyup->auto-submit#submit' } %>
        <%= form.submit 'Search it', class: 'bg-blue-400 text-white p-2 rounded hover:bg-blue-500 shadow-xl shadow-gray-300 transition ease-in-out hover:shadow-gray-400 hover:p-2.5' %>
      </div>
    <% end %>
    <%= turbo_frame_tag "last_queries" do %>
      <%= render partial: 'search_queries/partials/query_results', locals: { articles: Article.none } %>
    <% end %>
  </div>
</div>

<%= turbo_frame_tag "sub_menu" do %>
  <%= render partial: 'search_queries/partials/trending', locals: { trending: all_trending_queries } %>
<% end %>

app/views/search_queries/partials/_analytics.html.erb
<%= turbo_frame_tag "sub_menu" do %>
  <div>
    <div class="mt-4 mb-2 flex justify-between">
      <h2 class="font-bold text-xl ml-2"> Analytics about your searches</h2>
      <div class="text-gray-600">Total Searches: <%= SearchQuery.where(ip_address: request.remote_ip).count %></div>
    </div>
    <div class="flex items-center mb-4">
      <div class="mx-2 bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition ease-in-out">
        <%= link_to "All Your Searches", analytics_search_queries_path, data: { turbo_stream: true } %>
      </div>
      <div class="mx-2 bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition ease-in-out">
        <%= link_to "🔝 Your Top 10 Searches", top_search_queries_path, data: { turbo_stream: true } %>
      </div>
    </div>
  </div>
  <%= turbo_frame_tag "analytics" do %>
    <div clas="flex flex-col items-center justify-center bg-gray-200 p-8 rounded-lg shadow-lg">
      <% analytics.each_with_index do |analytics, index| %>
        <div class="mx-auto bg-white w-full p-2 mb-2 ml-2 rounded shadow">
          <h2 class="text-xl font-semibold">
            <%= "#{index + 1}." %> <%= format_analytics_information(analytics) %>
          </h2>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/search_queries/partials/_query_results.html.erb
<%= turbo_frame_tag "last_queries" do %>
  <% if articles.any? %>
    <div class="w-1/4 bg-white flex flex-col pr-2 pt-2 rounded-lg shadow-lg mt-2 absolute">
      <% articles.each do |article| %>
        <div class="p-4 mb-2 ml-2 rounded shadow cursor-pointer hover:bg-gray-100" 
             onclick="document.getElementById('search_query_term').value='<%= article.title %>'">
          <h2 class="text-xl font-semibold"><%= article.title %></h2>
        </div>
      <% end %>
    </div>
    <% end %>
<% end %>

app/views/search_queries/partials/_top_ten_queries_analytics.html.erb
<%= turbo_frame_tag "analytics" do %>
  <div clas="flex flex-col items-center justify-center bg-gray-200 p-8 rounded-lg shadow-lg">
    <% analytics.each_with_index do |analytics, index| %>
      <div class="mx-auto bg-white w-full p-2 mb-2 ml-2 rounded shadow">
        <h2 class="text-xl font-semibold">
          <%= "#{index + 1}." %> <%= format_top_ten_information(analytics) %>
        </h2>
      </div>
    <% end %>
  </div>
<% end %>

app/views/search_queries/partials/_trending.html.erb
<%= turbo_frame_tag "sub_menu" do %>
  <div class="mt-4 mb-2">
    <h2 class="font-bold text-xl ml-2"> Trending Searches 🔥</h2>
  </div>
  <div clas="flex flex-col items-center justify-center bg-gray-200 p-8 rounded-lg shadow-lg">
    <% trending.each_with_index do |trend, index| %>
      <div class="mx-auto bg-white w-full p-2 mb-2 ml-2 rounded shadow">
        <h2 class="text-xl font-semibold">
          <%= "#{index + 1}." %> <%= format_trend_information(trend) %>
        </h2>
      </div>
    <% end %>
  </div>
<% end %>